name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on the 'main' branch. Change it as needed.

jobs:
  deploy:
    name: Deploy Laravel Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies on GitHub runner
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php8.2 php8.2-mysql php8.2-xml php8.2-mbstring php8.2-zip php8.2-bcmath php8.2-curl
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Prepare Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$EC2_IP_ADDRESS << 'EOF'

            # Navigate to the Laravel app directory
            cd /var/www/html/order-management

            # Pull the latest code
            git pull origin main

            # Install dependencies
            composer install --no-dev --prefer-dist --optimize-autoloader

            # Run migrations
            php artisan migrate --force

            # Clear and cache configurations
            php artisan optimize:clear
            php artisan test

            # Restart nginx service to apply changes
            sudo service nginx restart
            sudo service php8.2-fpm restart
          EOF
      - name: Clean up
        run: rm private_key.pem
