name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployments from

jobs:
  deploy:
    name: Deploy Laravel Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli zip unzip curl
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Prepare Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: |
          php artisan test

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$EC2_IP_ADDRESS << 'EOF'
            sudo dpkg -l | grep php | tee packages.txt
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install -y php8.2 php8.2-mysql php8.2-xml php8.2-mbstring php8.2-zip
            cd /var/www/html/order-management
            git pull origin main
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            sudo service nginx restart
          EOF

      - name: Clean up
        run: rm private_key.pem
